.

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,6 +1,6 @@
 name: Deploy
 on:
-  push:
+  pull_request:
     branches: [ main ]
 jobs:
   deploy-logging:
@@ -19,30 +19,6 @@ jobs:
         run: docker build --tag $DOCKER_IMAGE .
       - name: Push to container registry
         run: docker push $DOCKER_IMAGE
-  run-mdtpbox:
-    needs: deploy-logging
-    runs-on: ubuntu-latest
-    env:
-      NAME: server-logging
-      DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
-    steps:
-      - name: executing remote ssh commands
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.MDTPBOX_URL }}
-          username: ${{ secrets.MDTPBOX_USER }}
-          key: ${{ secrets.MDTPBOX_SSH_KEY }}
-          port: ${{ secrets.MDTPBOX_PORT }}
-          envs: NAME,DOCKER_IMAGE
-          script_stop: true
-          script: |
-            docker pull ${DOCKER_IMAGE}
-            docker stop ${NAME} && docker rm ${NAME} || true
-            docker run \
-                --name ${NAME} \
-                --detach \
-                --restart on-failure \
-                ${DOCKER_IMAGE}
   run-apibox:
     needs: deploy-logging
     runs-on: ubuntu-latest
@@ -67,51 +43,75 @@ jobs:
                 --detach \
                 --restart on-failure \
                 ${DOCKER_IMAGE}
-  run-certbox:
-    needs: deploy-logging
-    runs-on: ubuntu-latest
-    env:
-      NAME: server-logging
-      DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
-    steps:
-      - name: executing remote ssh commands
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.CERTBOX_URL }}
-          username: ${{ secrets.CERTBOX_USER }}
-          key: ${{ secrets.CERTBOX_SSH_KEY }}
-          port: ${{ secrets.CERTBOX_PORT }}
-          envs: NAME,DOCKER_IMAGE
-          script_stop: true
-          script: |
-            docker pull ${DOCKER_IMAGE}
-            docker stop ${NAME} && docker rm ${NAME} || true
-            docker run \
-                --name ${NAME} \
-                --detach \
-                --restart on-failure \
-                ${DOCKER_IMAGE}
-  run-workerbox:
-    needs: deploy-logging
-    runs-on: ubuntu-latest
-    env:
-      NAME: server-logging
-      DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
-    steps:
-      - name: executing remote ssh commands
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.WORKERBOX_URL }}
-          username: ${{ secrets.WORKERBOX_USER }}
-          key: ${{ secrets.WORKERBOX_SSH_KEY }}
-          port: ${{ secrets.WORKERBOX_PORT }}
-          envs: NAME,DOCKER_IMAGE
-          script_stop: true
-          script: |
-            docker pull ${DOCKER_IMAGE}
-            docker stop ${NAME} && docker rm ${NAME} || true
-            docker run \
-                --name ${NAME} \
-                --detach \
-                --restart on-failure \
-                ${DOCKER_IMAGE}
+  # run-certbox:
+  #   needs: deploy-logging
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     NAME: server-logging
+  #     DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
+  #   steps:
+  #     - name: executing remote ssh commands
+  #       uses: appleboy/ssh-action@master
+  #       with:
+  #         host: ${{ secrets.CERTBOX_URL }}
+  #         username: ${{ secrets.CERTBOX_USER }}
+  #         key: ${{ secrets.CERTBOX_SSH_KEY }}
+  #         port: ${{ secrets.CERTBOX_PORT }}
+  #         envs: NAME,DOCKER_IMAGE
+  #         script_stop: true
+  #         script: |
+  #           docker pull ${DOCKER_IMAGE}
+  #           docker stop ${NAME} && docker rm ${NAME} || true
+  #           docker run \
+  #               --name ${NAME} \
+  #               --detach \
+  #               --restart on-failure \
+  #               ${DOCKER_IMAGE}
+  # run-workerbox:
+  #   needs: deploy-logging
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     NAME: server-logging
+  #     DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
+  #   steps:
+  #     - name: executing remote ssh commands
+  #       uses: appleboy/ssh-action@master
+  #       with:
+  #         host: ${{ secrets.WORKERBOX_URL }}
+  #         username: ${{ secrets.WORKERBOX_USER }}
+  #         key: ${{ secrets.WORKERBOX_SSH_KEY }}
+  #         port: ${{ secrets.WORKERBOX_PORT }}
+  #         envs: NAME,DOCKER_IMAGE
+  #         script_stop: true
+  #         script: |
+  #           docker pull ${DOCKER_IMAGE}
+  #           docker stop ${NAME} && docker rm ${NAME} || true
+  #           docker run \
+  #               --name ${NAME} \
+  #               --detach \
+  #               --restart on-failure \
+  #               ${DOCKER_IMAGE}
+  # run-mdtpbox:
+  #   needs: deploy-logging
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     NAME: server-logging
+  #     DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
+  #   steps:
+  #     - name: executing remote ssh commands
+  #       uses: appleboy/ssh-action@master
+  #       with:
+  #         host: ${{ secrets.MDTPBOX_URL }}
+  #         username: ${{ secrets.MDTPBOX_USER }}
+  #         key: ${{ secrets.MDTPBOX_SSH_KEY }}
+  #         port: ${{ secrets.MDTPBOX_PORT }}
+  #         envs: NAME,DOCKER_IMAGE
+  #         script_stop: true
+  #         script: |
+  #           docker pull ${DOCKER_IMAGE}
+  #           docker stop ${NAME} && docker rm ${NAME} || true
+  #           docker run \
+  #               --name ${NAME} \
+  #               --detach \
+  #               --restart on-failure \
+  #               ${DOCKER_IMAGE}
